// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdrrwktnwdcirkdyzpqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkcnJ3a3Rud2RjaXJrZHl6cHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NzU4ODYsImV4cCI6MjA2NjA1MTg4Nn0.nXVtIX1BTF1v-_DfIoTW0HyNJVuQc_4EupQTXShKFxI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);