// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uuljwfrsyrngiujliuxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1bGp3ZnJzeXJuZ2l1amxpdXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTQ4NDEsImV4cCI6MjA2NTk5MDg0MX0._iViHtGeNGuZu9XqGg5DFu7OcN2IU225FFcBiwFLo8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);